"""GAIRA assessment status and type constants."""

ASSESSMENT_TYPE_AI_RISK_LEVELS = "ai_risk_levels"
ASSESSMENT_TYPE_GAIRA_LIGHT = "gaira_light"
ASSESSMENT_TYPE_GAIRA_COMPREHENSIVE = "gaira_comprehensive"
ASSESSMENT_TYPE_AI_ACT_CHECK = "ai_act_check"
ASSESSMENT_TYPE_COMPLIANCE_CHECK = "compliance_check"

ASSESSMENT_TYPES = (
    ASSESSMENT_TYPE_AI_RISK_LEVELS,
    ASSESSMENT_TYPE_GAIRA_LIGHT,
    ASSESSMENT_TYPE_GAIRA_COMPREHENSIVE,
    ASSESSMENT_TYPE_AI_ACT_CHECK,
    ASSESSMENT_TYPE_COMPLIANCE_CHECK,
)

STATUS_DRAFT = "draft"
STATUS_IN_REVIEW = "in_review"
STATUS_SUBMITTED = "submitted"
STATUS_SUPERSEDED = "superseded"

GAIRA_STATUS_NONE = "none"
GAIRA_STATUS_IN_PROGRESS = "in_progress"
GAIRA_STATUS_DONE = "done"

CHECK_STATUS_NONE = "none"
CHECK_STATUS_IN_PROGRESS = "in_progress"
CHECK_STATUS_DONE = "done"
