"""Analytics query constants (Sprint 3 Step 7)."""

from app.services.events.constants import (
    EXECUTION_BLOCKED,
    EXECUTION_INTERRUPTED,
    GUARD_OUTPUT_BLOCKED,
    GUARD_PROMPT_BLOCKED,
    OUTPUT_BLOCKED,
    POLICY_VIOLATION,
    PROMPT_BLOCKED,
    RULE_TRIGGERED,
    SUSPICIOUS_ACTIVITY,
)

VIOLATION_EVENT_TYPES: tuple[str, ...] = (
    PROMPT_BLOCKED,
    OUTPUT_BLOCKED,
    POLICY_VIOLATION,
    SUSPICIOUS_ACTIVITY,
    EXECUTION_BLOCKED,
    EXECUTION_INTERRUPTED,
    GUARD_PROMPT_BLOCKED,
    GUARD_OUTPUT_BLOCKED,
    RULE_TRIGGERED,
)

BLOCKED_EXECUTION_STATUSES: tuple[str, ...] = ("blocked", "interrupted")

GRANULARITY_HOUR = "hour"
GRANULARITY_DAY = "day"
GRANULARITY_WEEK = "week"

HIGH_RISK_SCORE_THRESHOLD = 70
