"""Prompt monitoring constants (Sprint 3 Step 3)."""

DECISION_ALLOW = "allow"
DECISION_WARN = "warn"
DECISION_BLOCK = "block"

DECISIONS: frozenset[str] = frozenset({DECISION_ALLOW, DECISION_WARN, DECISION_BLOCK})

DECISION_ORDER: dict[str, int] = {
    DECISION_ALLOW: 0,
    DECISION_WARN: 1,
    DECISION_BLOCK: 2,
}

# Finding types
FINDING_API_KEY = "api_key"
FINDING_PASSWORD = "password"
FINDING_EMAIL = "email"
FINDING_PHONE = "phone"
FINDING_SSN = "ssn"
FINDING_CREDIT_CARD = "credit_card"
FINDING_BANK_ACCOUNT = "bank_account"
FINDING_FINANCIAL = "financial_data"
FINDING_HEALTHCARE = "healthcare_data"
FINDING_PII = "pii"
FINDING_CONFIDENTIAL = "confidential_data"
FINDING_PROMPT_INJECTION = "prompt_injection"
FINDING_JAILBREAK = "jailbreak"
FINDING_SUSPICIOUS_INSTRUCTION = "suspicious_instruction"

# Per-finding default enforcement (can be overridden by severity)
FINDING_DEFAULT_DECISION: dict[str, str] = {
    FINDING_API_KEY: DECISION_BLOCK,
    FINDING_PASSWORD: DECISION_BLOCK,
    FINDING_PROMPT_INJECTION: DECISION_BLOCK,
    FINDING_JAILBREAK: DECISION_BLOCK,
    FINDING_SSN: DECISION_BLOCK,
    FINDING_CREDIT_CARD: DECISION_BLOCK,
    FINDING_BANK_ACCOUNT: DECISION_WARN,
    FINDING_FINANCIAL: DECISION_WARN,
    FINDING_HEALTHCARE: DECISION_WARN,
    FINDING_EMAIL: DECISION_WARN,
    FINDING_PHONE: DECISION_WARN,
    FINDING_PII: DECISION_WARN,
    FINDING_CONFIDENTIAL: DECISION_WARN,
    FINDING_SUSPICIOUS_INSTRUCTION: DECISION_WARN,
}

SEVERITY_WEIGHTS: dict[str, int] = {
    "low": 5,
    "medium": 15,
    "high": 28,
    "critical": 45,
}

RISK_SCORE_BLOCK_MIN = 70
RISK_SCORE_WARN_MIN = 35
RISK_SCORE_MAX = 100

MAX_PROMPT_LENGTH = 32_000
MASKED_PROMPT_MAX_STORE = 4_000
